#pragma once

#include "driver/gpio.h"

#define APP_NAME "ble-kvm-switch"

// Keep GPIO19/GPIO20 free for native USB D-/D+ on ESP32-S3.
#define PIN_BUTTON_LEFT GPIO_NUM_4
#define PIN_BUTTON_RIGHT GPIO_NUM_5
#define PIN_LED_LEFT GPIO_NUM_6
#define PIN_LED_RIGHT GPIO_NUM_7
#define PIN_BUZZER GPIO_NUM_8

#define PIN_I2C_SDA GPIO_NUM_10
#define PIN_I2C_SCL GPIO_NUM_11
#define I2C_PORT I2C_NUM_0
#define I2C_FREQ_HZ 400000

#define BUTTON_DEBOUNCE_MS 35
#define BUTTON_LONG_PRESS_MS 1500
#define BUTTON_STUCK_PRESS_MS 6000
#define BUTTON_SCAN_MS 20
#define KVM_EVENT_QUEUE_DEPTH 32
#define MOUSE_REPORT_QUEUE_DEPTH 32
#define MOUSE_BLE_DELTA_SCALE 2
#define MOUSE_BLE_REPORT_INTERVAL_MS 8
#define MOUSE_BLE_LOG_INTERVAL_MS 1000

#define UI_REFRESH_MS 250
#define USB_STUB_HEARTBEAT_MS 1000
#define BLE_STUB_HEARTBEAT_MS 1500
